### ISSUE TITLE
Git  Clone succeeded, but checkout failed

### ISSUE THREAD

**Issue by hwy1782** [LjyYano/Thinking_in_Java_MindMapping#11]
在 windows  10 环境下执行 clone 时报错，具体如下：

![image](https://user-images.githubusercontent.com/2442046/191395496-b99f2446-a00b-498e-92a0-63d913e86aae.png)

查询了下错误原因应该是：

> 在win10下 | 属于特殊字符不能用作文件名

博主能否修改下这个文件名，方便win10下用户

**Comment by LjyYano** [comment]
@hwy1782 你好，当时正在休假，忘记回复了~已经修改

**Comment by feihong247** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
