### ISSUE TITLE
咨询一个问题

### ISSUE THREAD

**Issue by youbooks** [LjyYano/Thinking_in_Java_MindMapping#2]
感谢作者的分享，那个JAVA编程思想 思维导图，导图里面贴出来的代码好像特别少，后续作者有空能否多补上代码？

**Comment by LjyYano** [comment]
你好，我是在读这本书的时候，将认为重要的点记录下来。至于代码并没有全部贴上，很多代码都过时了。《Java编程思想》第4版是基于Java 6 的吧？现在都出Java 11 了。

**Comment by LjyYano** [comment]
> 感谢作者的分享，那个JAVA编程思想 思维导图，导图里面贴出来的代码好像特别少，后续作者有空能否多补上代码？

你好，我是在读这本书的时候，将认为重要的点记录下来。至于代码并没有全部贴上，很多代码都过时了。《Java编程思想》第4版是基于Java 6 的吧？现在都出Java 11 了。
