### ISSUE TITLE
这句话有问题：完全面向对象：这是Java最大的优点，但是也是很大的缺点。

### ISSUE THREAD

**Issue by lyunclesam** [LjyYano/Thinking_in_Java_MindMapping#3]
完全面向对象：这是Java最大的优点，但是也是很大的缺点。 
这句话有问题，Java并不是完全面向对象，在《Java编程思想》有提到过Java并不是一个纯粹的百分百的面向对象语言，最简单的证明就是，她的那些基本数据类型

**Comment by LjyYano** [comment]
@lyunclesam 嗯，Java除了基本数据类型，还算是完全的面向对象吧~甚至连异常都是对象。基本类型是个特例

**Comment by m5j** [comment]
> 完全面向对象：这是Java最大的优点，但是也是很大的缺点。
> 这句话有问题，Java并不是完全面向对象，在《Java编程思想》有提到过Java并不是一个纯粹的百分百的面向对象语言，最简单的证明就是，她的那些基本数据类型

根本就没有百分百纯粹的面向对象语言

**Comment by LjyYano** [comment]
@m5j 我感觉在语法层面，Kotlin算是完全面向对象了，只不过Java为了效率，做了折中
