### ISSUE TITLE
请问鸟哥的linux私房菜的思维导图还有吗？

### ISSUE THREAD

**Issue by ypan87** [LjyYano/Thinking_in_Java_MindMapping#5]
您好，请问鸟哥的linux私房菜的思维导图还有吗

**Comment by LjyYano** [comment]
你好，有的~https://github.com/LjyYano/Thinking_in_Java_MindMapping/blob/master/%E6%80%9D%E7%BB%B4%E5%AF%BC%E5%9B%BE-Linux%E7%B3%BB%E7%BB%9F%E5%91%BD%E4%BB%A4%E5%8F%8AShell%E8%84%9A%E6%9C%AC.mmap

这个是综合了Linux私房菜的，可以转成xmind格式打开
