### ISSUE TITLE
大佬的思维导图都撤掉了吗？

### ISSUE THREAD

**Issue by xiaomingjie** [LjyYano/Thinking_in_Java_MindMapping#7]
查到java编程思想的思维导图查过来的，但是好像资源已经没了，大佬能再维护一下吗？

**Comment by LjyYano** [comment]
好的，我这两天加上。主要是那几个思维导图太大了

**Comment by LjyYano** [comment]
> 查到java编程思想的思维导图查过来的，但是好像资源已经没了，大佬能再维护一下吗？

你好，这个已经上传了哈~这个思维导图是根据《Java编程思想》做的，但是这本书是基于Java 6的，已经过时了。预计明年原作者的新版《Java编程思想》会发布~

**Comment by LjyYano** [comment]
已经上传了
